server:
  port: 8081    # HTTP(Tomcat) Port，端口自定义
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/zysoft_agriculture_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai #数据库连接池（druid）
    driverClassName: com.mysql.jdbc.Driver
